# -*- coding: utf-8 -*-
"""NLP_LP_b2_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KGBZmmnzCVoiOQJPDqoIMYt04NMw6i6r
"""

from transformers import pipeline

# Load the classification pipeline with the specified model
pipe = pipeline("text-classification",
                model="tabularisai/multilingual-sentiment-analysis")

# Classify a new sentence
#sentence = "I love this product! It's amazing and works perfectly."
sentence = "The food was not so good."
result = pipe(sentence)

# Print the result
print(result)

from transformers import pipeline
sentiment = pipeline("sentiment-analysis")
sentiment("I love this!")

from transformers import pipeline

summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

text = """
AI is moving fast and it’s more than hype. As advancements in agentic AI present significant opportunities for organizations, this report breaks down the most critical AI trends that will reshape how software is developed, deployed, and scaled.

Whether you're building internal applications or transforming customer experiences, now is the time to understand which AI innovations are worth investing in and how to strategically prepare your tech stack for what’s coming.

Actionable insights for IT and business leaders
Uncover the key technologies and trends that will define how AI is used across the software development lifecycle. Learn how to adapt your strategy, prioritize the right tools, and prepare your teams for the next wave of innovation.

As you read this report, we recommend you consider our following key takeaways:

How advanced AI is driving automation, problem-solving, and decision-making across industries.
Ways agentic AI will create significant opportunities to improve productivity, customer experience, and decision-making, but it will require user trust to gain sustained adoption.
Strategies for managing AI risks, compliance, and responsible adoption.
Key insights on where AI is headed and how to build a competitive advantage.
Gartner, Emerging Tech Impact Radar: Generative AI, Annette Zimmermann, Danielle Casey, 14 February 2025. GARTNER is a registered trademark and service mark of Gartner, Inc. and/or its affiliates in the U.S. and internationally and is used herein with permission. All rights reserved.
"""

print(summarizer(text , max_length = 100)[0]['summary_text'])

"""**Text Generation**"""

from transformers import pipeline, set_seed
generator = pipeline('text-generation', model='gpt2')

output = generator("In the future, artificial intelligence will",
                   max_length = 30,
                   num_return_sequences = 5)

print(output[0])

print(output[1])

print(output[2])

print(output[3])

print(output[4])

"""**GPT_OSS_20b**"""

from transformers import pipeline
import torch

model_id = "openai/gpt-oss-20b"

pipe = pipeline(
    "text-generation",
    model=model_id)

